### PR TITLE
Brush up buildout

### PR DESCRIPTION
**Pull request by reinhardt**
Added Makefile. Also aligned requirements.txt with versions.cfg.

On my local machine, `make` always runs `pip install` and `buildout`. I would expect it to only run when `.installed.cfg` or a dependency are out of date. I noticed that manually touching files makes a difference:

```
oira@oira:~/oira.application.buildout (master +)
[10:19:32]$ make bin/buildout
./bin/pip install -IUr requirements.txt
[...]
^CERROR: Operation cancelled by user
[...]
make: *** [Makefile:9: bin/buildout] Error 1

oira@oira:~/oira.application.buildout (master +)
[10:19:49]$ make bin/pip
make: 'bin/pip' is up to date.
oira@oira:~/oira.application.buildout (master +)
[10:19:56]$ touch bin/buildout
oira@oira:~/oira.application.buildout (master +)
[10:20:23]$ make bin/buildout
make: 'bin/buildout' is up to date.
```

@ale-rt, @pysailor, do you have any idea why that is?

Refs [SCR-1768](https://jira.syslab.com/browse/SCR-1768)

### CODE REVIEW

**Comment by ale-rt** [comment]
Running buildout generates a bin/buildout. I would create the venv in a py3 folder like it is done here https://gitlab.com/syslabcom/quaive/quaivesaas.buildout/-/blob/master/Makefile

**Comment by reinhardt** [comment]
Ah! Interesting. I was wondering why there is this `py3` subfolder.

@pysailor, do you think it's worth switching from the existing virtualenv in the buildout root to one in `py3` as Ale says? Or do we accept that buildout is run every time `make` is issued? (`make upgrade` and `make restart` are not affected)

**Comment by reinhardt** [comment]
We can even merge this now and tweak it later.

**Comment by pysailor** [comment]
Hi @reinhardt 
thanks for this!
Using a dedicated py3 subfolder seems to be a pattern in several of our recent projects. In light of unification, I would also recommend to use this for OSHA.

**Comment by reinhardt** [comment]
OK!

@ale-rt, do you have any experience switching from an existing venv in the buildout root to one in a subfolder? We should probably clean up the existing one to avoid confusion/errors, right?

**Comment by pysailor** [comment]
We can just as well do this manually (or tell the hoster how to do this, respectively), since it's a one-off thing.

**Comment by reinhardt** [comment]
Cool. I've changed the Makefile accordingly.

When first running make with the new style I got a version conflict. I suppose we can manually fix that if we need manual intervention anyway (`py3/bin/pip install setuptools==42.0.2`).

```
[15:48:32]$ make
python3 -m venv py3 || virtualenv -p python3 --no-site-packages --no-setuptools py3 || virtualenv -p python3 --no-setuptools py3
./py3/bin/pip install -IUr requirements.txt
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Ignoring certifi: markers 'platform_system == "Windows"' don't match your environment
Ignoring ntfsutils: markers 'platform_system == "Windows" and python_version < "3.0"' don't match your environment
Collecting setuptools==42.0.2
  Using cached setuptools-42.0.2-py2.py3-none-any.whl (583 kB)
Collecting zc.buildout==2.13.4
  Using cached zc.buildout-2.13.4-py2.py3-none-any.whl (153 kB)
Collecting wheel==0.36.2
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, zc.buildout, wheel
Successfully installed setuptools-56.0.0 wheel-0.36.2 zc.buildout-2.13.4
WARNING: You are using pip version 21.1.1; however, version 22.0.3 is available.
You should consider upgrading via the '/srv/oira/oira.application.buildout/py3/bin/python3 -m pip install --upgrade pip' command.
./py3/bin/buildout
Version and requirements information containing setuptools:
  Requirement of mr.developer==2.0.1: setuptools
  Requirement of zc.buildout: setuptools<52,>=8.0
While:
  Installing.
  Loading extensions.
Error: There is a version conflict.
We already have: setuptools 56.0.0
but zc.buildout 2.13.4 requires 'setuptools<52,>=8.0'.
make: *** [Makefile:12: .installed.cfg] Error 1
```

**Comment by pysailor** [comment]
I saw the same error yesterday when I deployed daimler INT, in the MailDev component.
I fixed it by manually installing the setuptools version defined in [requirements.txt](https://github.com/ale-rt/buildout.maildev/blob/master/requirements.txt):
`./py3/bin/pip install setuptools==51.3.3`

So I don't know what part insists on installing the latest version of setuptools or how to avoid it.

**Comment by ale-rt** [comment]
> OK!
> 
> @ale-rt, do you have any experience switching from an existing venv in the buildout root to one in a subfolder? We should probably clean up the existing one to avoid confusion/errors, right?

I generally `rm -rf bin lib* share and whatever`.
YMMV

**Comment by reinhardt** [comment]
FWIW the latest setuptools version is there when creating the venv and doesn't get downgraded when installing the requirements.

But let's not worry about it and fix it by hand, OK?

Any more wishes or remarks? From my point of view this is ready to merge.

**Review by pysailor — APPROVED** [review]
LGTM

**Pull request merged**
